


server:
  port: 8080

spring:
  application:
    name: ticket_go
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goticket?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    #url: jdbc:mysql://localhost:3306/goticket
    username: springstudent
    password: springstudent

  mail:
    host: smtp.gmail.com
    port: 587
    username: helloticketgo@gmail.com
    password: ttjc sbnj mrkc rsjf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#springdoc相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'hyc'
      paths-to-match: '/**'
      packages-to-scan: com.ticketgo  #改成你自己的包名，一般到启动类的包名

#knife4j相关配置 可以不用改
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类

